# Generated by Django 5.1.6 on 2025-07-18 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100)),
                ('topic_name', models.CharField(max_length=256)),
                ('subtopic_name', models.CharField(max_length=256)),
                ('notes', models.TextField(blank=True, null=True)),
                ('quizzes', models.JSONField(blank=True, null=True)),
                ('quiz_score', models.PositiveIntegerField(blank=True, null=True)),
                ('project', models.TextField(blank=True, null=True)),
                ('project_score', models.PositiveIntegerField(blank=True, null=True)),
                ('project_repo', models.URLField(blank=True, null=True)),
                ('ai_feedback', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course_id', 'topic_name', 'subtopic_name')},
            },
        ),
    ]
