# Generated by Django 5.1.6 on 2025-07-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='project_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='quiz_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
