# Generated by Django 5.1.6 on 2025-08-02 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_course_project_status_course_quiz_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Gen_Content',
        ),
        migrations.CreateModel(
            name='CoursePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_slug', models.SlugField(max_length=200)),
                ('level', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('goal', models.TextField(blank=True)),
                ('status', models.CharField(default='In progress', max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=0)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course_slug')},
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('topic_slug', models.SlugField(max_length=255)),
                ('course_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='myapp.courseplan')),
            ],
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('video_title', models.CharField(blank=True, max_length=512, null=True)),
                ('video_link', models.URLField(blank=True, max_length=512, null=True)),
                ('video_author', models.CharField(blank=True, max_length=255, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='myapp.module')),
            ],
        ),
    ]
