# Generated by Django 5.1.6 on 2025-08-09 07:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_course_gen_content_courseplan_module_subtopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_input_type', models.CharField(choices=[('PDF', 'PDF Resume'), ('TEXT', 'Skills Text')], max_length=10)),
                ('user_input_content', models.TextField()),
                ('resume_pdf_data', models.BinaryField(blank=True, null=True)),
                ('resume_pdf_name', models.CharField(blank=True, max_length=255, null=True)),
                ('current_question_index', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('user_answer', models.TextField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('timestamp_asked', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_answered', models.DateTimeField(blank=True, null=True)),
                ('needs_clarification', models.BooleanField(default=False)),
                ('clarification_prompt', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='myapp.interviewsession')),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
    ]
