# Generated by Django 5.1.6 on 2025-08-16 09:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_interviewsession_interviewquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic',
            name='video_author',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='video_link',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='video_title',
        ),
        migrations.AddField(
            model_name='module',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='module',
            name='video_author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='video_link',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='video_title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
