# Generated by Django 5.1.6 on 2025-08-31 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_subtopic_video_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePlanOnSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus', models.BinaryField()),
                ('syllabus_text', models.TextField()),
                ('resources', models.BinaryField(blank=True, null=True)),
                ('resources_text', models.TextField(blank=True, null=True)),
                ('course_name', models.CharField(max_length=200)),
                ('course_slug', models.SlugField(max_length=200)),
                ('status', models.CharField(default='In progress', max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=0)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course_slug')},
            },
        ),
        migrations.CreateModel(
            name='ModuleOnSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('topic_slug', models.SlugField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='myapp.courseplanonsyllabus')),
            ],
        ),
        migrations.CreateModel(
            name='SubtopicOnSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='myapp.moduleonsyllabus')),
            ],
        ),
    ]
